# Generated by Django 3.0.6 on 2021-04-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('musician_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'musicians',
            },
        ),
        migrations.CreateModel(
            name='Music_Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('date_of_release', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Musicians')),
            ],
            options={
                'db_table': 'music_albums',
            },
        ),
    ]
