# Generated by Django 3.0.6 on 2021-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_albums',
            name='price',
            field=models.IntegerField(verbose_name=range(100, 1000)),
        ),
    ]
