# Generated by Django 3.0.6 on 2021-04-10 06:54

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210410_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_albums',
            name='price',
            field=models.IntegerField(validators=[myapp.models.validate_number]),
        ),
    ]
