# Generated by Django 3.0.6 on 2021-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210410_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_albums',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music_albums',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
